site_name: QA Technical Doc site [Draft]
theme:
  name: material


nav:
    - Home: 'index.md'

    - Tooling:
        - 'UI Automation': 'ui-automation.md'
        - 'API Automation': 'api-automation.md'
        - 'Desktop Automation': 'desktop-automation.md'

    - FAQs: 'faqs.md'

